### ISSUE TITLE
ImportError: No module named 'remoteApiBindings'

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#102]
As you can see in this [travis-ci build](https://travis-ci.org/poppy-project/pypot/jobs/71688919), there is an import Error of remoteApiBindings. Any idea @pierre-rouanet ?

**Comment by pierre-rouanet** [comment]
Maybe fixed by 61439815c0b25d30bfb1249668bd646f0c0e0a43 ?

**Comment by show0k** [comment]
Fix by a066182c92970875a1f00baa4eb0b9b0ead46030, I was just starting my test script in the pypot directory, so 2to3 was nod used.
