### ISSUE TITLE
Managing the way primitives are combined

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/pypot#12]
By default, the manager take the mean of primitives orders. Until now, to change this behaviour, the easiest way was to edit the default parameter directly in the Primitive manager classe. For example:
```python
class PrimitiveManager(threading.Thread):
    def __init__(self, motors, freq=50, filter=partial(numpy.mean, axis=0)):
```
to
```python
class PrimitiveManager(threading.Thread):
    def __init__(self, motors, freq=50, filter=partial(numpy.sum, axis=0)):
```

But since a week, pypot can be installed using **pip** or **easy_install**. This means it is less relevant to ask people to find source and change it.

**It is maybe time to try some new features allowing to tune this parameter easily** ?

A first quick&ugly patch could be to add a method to change the filter of the manager. 
For example:

```python
class PrimitiveManager(threading.Thread):
    def __init__(self, motors, freq=50, filter=partial(numpy.mean, axis=0)):

    [...]

    @property
    def primitive_filter(self):
        return self._filter

    @primitive_filter.getter
    def primitive_filter(self, new_filter):
        self._filter = new_filter
```

However, having the same filter for all parameters of all primitives is maybe not always desirable.
For example, we would like to sum position to have relative motion. At the same time, summing torque_limit parameter can lead to have torque_limit >100%. It is even worse with the tuning of PID gains ...

So it becomes a complex problem and should be discussed. Yet I do not know where it should be, here in the github issues or on the [poppy forum](https://forum.poppy-project.org/) ?

**Comment by damiencaselli** [comment]
After a year and a half of inactivity, I hereby declare this issue as closed.
