### ISSUE TITLE
Investigate PID register in MX28 firmware

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#128]
The "new" MX28 firmware seems to have  change the order of the [PID register to a DIP](http://support.robotis.com/en/product/dynamixel/mx_series/mx-28.htm).

 " __The control table’s order for PID has changed to DIP from this version onwards. Please make reference of this change.__"
But... it is not sure of which version changed this feature.

**Comment by show0k** [comment]
It seems a false alert.. This message is displayed a least [since 2012](http://support.robotis.com/en/product/dynamixel/mx_series/mx-28.htm).

**Comment by pierre-rouanet** [comment]
@show0k Shall we close this?
