### ISSUE TITLE
Write an alternative MovePlayer primitive without scipy

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#131]
Scipy is necessary only for the MovePlayer primitive. We intended to use it elsewhere but it wasn't done. Making scipy optional will facilitate the installation from pip on Linux, and it will facilitate the way to do a standalone executable for windows with the visualisator.

**Comment by pierre-rouanet** [comment]
Scipy is now also used by IKPy so I'm not sure this is relevant anymore?

**Comment by show0k** [comment]
Arf yeah... ikpy uses [scipy.optimize](https://github.com/scipy/scipy/blob/v0.17.0/scipy/optimize) and it would be difficult to embedded it in ikpy...
Closing.
