### ISSUE TITLE
Ideas for a new REST API

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#134]
Now a day we have two APIs: SnapRobotServer and HTTPRobotServer without any technical raisons. It would be useful to rewrite a new one.
We can use this issue to add ideas of usefull features we would like to add on it:
- can be used to instantiate the robot (for reseting)
- ability to get (download) and post (uplaod) a record file
-  the possibility to have different robot discussing to each other (@pierre-rouanet)
- can use websockets or server side events of enabling a long pooling mode which will reduce tcp connexion latency
- ...

[A good explanation](http://stackoverflow.com/a/16878494) of the differences between a REST and a resources-oriented API (the model behind SnapRobotServer and HTTPRobotServer).

**Comment by pierre-rouanet** [comment]
Good idea. Maybe we should split this in two:
* the REST API (which url for which features)
* the transport issue (web socket for instance)

On the API side, it would be useful to also think about the possibility to have different robot discussing to each other.

**Comment by show0k** [comment]
HTTP is the application layer (not the transport). An API cannot use Websockets and be REST. We'll have to do an abstract api (what it is actually made) and provide multiple ways for the end points : http and websockets.
