### ISSUE TITLE
LED register is not working very well on XL-320

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#144]
There is always some odd things with led register on the poppy-ergo-jr (it is a bug of Dxl320IO). 
@Tibo42 could you detail a protocol to reproduce the bug ?
@pierre-rouanet don't you think it should be solved for the next release ?

I checked [dxl_to_led_color](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/conversion.py#L256), [led_color_to_dxl](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/conversion.py#L260), and all the table of [DXL320IO registers](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/io/io_320.py), and I didn't see anything wrong...

**Comment by pierre-rouanet** [comment]
Yes I would love to solve it for the next release. But same as you I don't see anything wrong on our side. Could it be some Robotis "magic"?

**Comment by show0k** [comment]
For seeing if Its electronic magic or pypot issue we can try to send the command throw low level serial only, but I will be very surprised. 
Théo

**Comment by pierre-rouanet** [comment]
The problem seems to appear only when using primitives.
