### ISSUE TITLE
primitive pause method is broken

### ISSUE THREAD

**Issue by Tibo42** [poppy-project/pypot#163]
on Ergo_Jr when use url: 
`http://<nom_du_robot>:6969/primitive/<nom_primitive>/<action>`
action: start then stop are perform properly but when I use action: pause or resume the only effect is to make stop action ineffective.

**Comment by show0k** [comment]
I checked, and I confirm the issue (and no exception are raised).

**Comment by pierre-rouanet** [comment]
Should be fixed by https://github.com/poppy-project/pypot/pull/168. Tests are ok on my side.
