### ISSUE TITLE
l_knee_y is not bound to a function for goto_position

### ISSUE THREAD

**Issue by celiasmith** [poppy-project/pypot#193]
a line like this:
```
poppy.l_knee_y.goto_position(0,2)
```
Returns an error that a float isn't callable because it is a float! I believe it should be a bound function as e.g., ```poppy.head_z.goto_position()``` is.

There could be other non bound elements, I haven't looked.  I ran across this running the tutorial notebook, and using the knee instead of the head to go to a position.

**Comment by show0k** [comment]
You have probably overwritten the l_knee_y object (executed something like `poppy.l_knee_y = 42`). Re-instanciate *poppy* and it will be fine.

**Comment by celiasmith** [comment]
thanks.
