### ISSUE TITLE
location of .record file using snap

### ISSUE THREAD

**Issue by jjehl** [poppy-project/pypot#217]
Example : 
in rest.py line 151 
with open('{}.record'.format(move_name), 'w') as f:
            recorder.move.save(f)

The file location will really depends on how you launched the snap server (jupyter, puppet master, wsgi, apache etc...) Maybe it could be better to fix the folder, using user_data_dir('snap', 'record') ?

**Comment by pierre-rouanet** [comment]
Yes, agreed! Do not hesitate to open a PR for this!
