### ISSUE TITLE
Move speed modification from Snap

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#230]
Movement recorded in Snap with a bought Poppy Ergo Jr are not able to speedup movements. The movement file is correctly read (the movement last less time) but the motor speed is not increased.

Need to investigate.

**Comment by show0k** [comment]
It was an old bug, with a pypot upgrade to 2.11.10.
I updated the conda corrsponded ARMv7 package.

**Comment by show0k** [comment]
This very strange bug is still present with pypot 3.0.1.
We should test more and push #237 to have a simpler implementation of Move recorder.

**Comment by jjehl** [comment]
Sure, on my fork it was pushed several months ago now.

**Comment by show0k** [comment]
Thanks for the feedback. Are you talking about https://github.com/Roboticia/pypoticia ?
