### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kmolLin** [poppy-project/pypot#239]
How to use the pypot with Personal machine.
And the Vrep setting ?
Have any documentation about ?

**Comment by show0k** [comment]
I'm not sure to understand, you want to control a simulated Poppy robot on your PC with V-REP ?
You have to install Python, the robot librairy and its dependancies, and VREP. No special settings are required on vrep.
More info on the [doc](https://docs.poppy-project.org/en/installation/install-poppy-softwares.html).

**Comment by kmolLin** [comment]
Thank's reply show0k Sorry I didn't talk correct question.
 My request is that I make a car and have four motor ,I want to use the pypot to simulation the car in the Vrep and real time. How did i setting the motor on the vrep or that need so someting to  simulation

**Comment by jjehl** [comment]
You need to build your robot as a pypot creature and to build the vrep model. Depends on your models but probalby many hours of work.

**Comment by kmolLin** [comment]
Thank you for your help. I sucessful develop a GUI to control the robot in Vrep with scene.
![image](https://cloud.githubusercontent.com/assets/8325379/24653009/9b9409cc-1966-11e7-9dea-209fb28d66bc.png)

**Comment by show0k** [comment]
So, is the issue resolved ?
