### ISSUE TITLE
RaspberryPi GPIO support with 74LS241

### ISSUE THREAD

**Issue by nick-zanobini** [poppy-project/pypot#248]
Is there any plans to add support for controlling the Dynamixel servos directly from the GPIO of the RaspberryPi using the 74LS241 IC to convert to half-duplex?

**Comment by show0k** [comment]
With the [pixl](https://github.com/poppy-project/pixl), there is a sort of autoswitch between RX and TX, so it doesn't need to add an orientation pin.

So, we don't plan add this functionality, but if you would like to use it, a PR is welcome.
It should require to modify [abstract_io](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/io/abstract_io.py) to add the orientation pin as an optional argument, and the [configuration parser](https://github.com/poppy-project/pypot/blob/master/pypot/robot/config.py) to expose this optional argument in the config file of the robot.
