### ISSUE TITLE
Security features

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/pypot#27]
During the Maker Faire, a Poppy motor has melted because it has reached an extremely high temperature.

We could of course run a safe primitive checking for temperature state but maybe there is another way, more low level, embedded in pypot avoiding to let a $250 motor broke it self just because user is stupid ? Maybe not ...

**Comment by show0k** [comment]
This is now fix by poppy-project/poppy-humanoid#10. Do we should add the primitive in pypot for making it more accessible ?
