### ISSUE TITLE
pypot install, ikpy fails

### ISSUE THREAD

**Issue by ThotAlion** [poppy-project/pypot#288]
the pip install fail for python 2.7, the ikpy module does not work.

**Comment by ymollard** [comment]
You may want to remove all mentions to `ikpy` in [setup.py](https://github.com/poppy-project/pypot/blob/master/setup.py#L23) but also in your creature definition if you have any.
@Phylliade should `ikpy` be removed from pypot?

**Comment by Phylliade** [comment]
The issue has been fixed in IkPy!

Actually, about the dependency, we could fix the IKPY version number in Pypot to v2.2.3, so regressions in new versions are avoided?

**Comment by ymollard** [comment]
It's even better! Feel free to update requirements, @Phylliade :)
