### ISSUE TITLE
[improvement] New poppy creature

### ISSUE THREAD

**Issue by hkerma** [poppy-project/pypot#292]
Hi !
Not quite sure if I should open an issue for that, anyway : I had a group project this year, which involved Poppy and some movement detection/replication. We needed to have wrist articulation on our Poppy so, with the help of researchers and teachers, we ended up with a complete poppy library (strongly based on poppy-humanoid), a real Poppy robot with its articulated wrists, a V-Rep scene featuring this model, etc. 

We thought that it could be a good idea to share it with the poppy-project.
We could discuss how far you guys want to deploy our feature : maybe only the library, or going further with adding this "poppy-wrist" as a base feature in pypot.creatures. We could also think of distributing the complete guide for building this Poppy (motors reference, .stl printable pieces, etc.)

Here's the [library](https://github.com/hkerma/poppy-wrist) : it's not already fine for sharing, as I wanted to check up everything with you, including the fact that some .stl pieces have been developped by our school's researchers and they wanted to be cited in the library.

Feel free to contact me on this issue, or by e-mail : hugo.kermabon-bobinnec@imt-atlantique.net

EDIT : I uploaded these images so you can see what the result looks like

![modified_poppy](https://user-images.githubusercontent.com/35636205/62876526-6c4dfa00-bd25-11e9-8576-6a28bfdf7a81.png) 
This is the final arm

![modified_poppy_vrep](https://user-images.githubusercontent.com/35636205/62876528-6ce69080-bd25-11e9-9762-ebc14874255a.png)
This is the V-Rep scene we modified to include the articulated wrist.

You can check [more](https://telefab.fr/2019/07/03/realisation-dune-orthese-permettant-la-detection-et-le-mouvement-robot/) about our school project, and see a video of poppy with wrist working :)

**Comment by ymollard** [comment]
Hugo, thank you for sharing your wrist project! Indeed, Github issues are made for issues. Please share your project on the forum so that people can ask questions and react: https://forum.poppy-project.org/c/community-projects
Documentation is important indeed, software and also hardware (e.g. videos): the more reproducible your work is, the faster it can be reinvested by the community.
