### ISSUE TITLE
Configuration json with baudrate

### ISSUE THREAD

**Issue by ozziest** [poppy-project/pypot#43]
How can I use baudrate with configurations? I don't find anything in documentation about it?

**Comment by pierre-rouanet** [comment]
At the moment the baud rate cannot be specified in the configuration. It has to be done "by hand". 

Do not hesitate to do a pull request.

**Comment by hthomas60** [comment]
I am having a similar problem. How would you change the baud rate by hand? I know how to change it using the low level API but I do not know how to change it once it is in the configuration. Thanks!

**Comment by show0k** [comment]
To change the baudrate you have to use the low level API, so the configuration file is not used.
