### ISSUE TITLE
compliant_behavior is not primitive manager proof.

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/pypot#61]
Merging a primitive with compliant_behavior = 'dummy' with 'safe' does not work so well :)

**Comment by pierre-rouanet** [comment]
Hum... this has some nasty implications ^^

The filter function will try to add those two values and you will end up with a 'dummysafe' compliant behavior... I guess for the moment the solution would be to define a specific filter where this case is checked and manually solved.

In the longer term, the management of primitives should be entirely re-written.
