### ISSUE TITLE
Dependency missing: "ImportError: No module named enum"

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/pypot#67]
When running the poppy-reset-motor:

```
  File "..pypot/pypot/dynamixel/conversion.py", line 18, in <module>
    from enum import Enum
ImportError: No module named enum
```

Patch:
```
pip install enum
```

I thought you just forget to put enum in the setup but there is a "enum34", maybe it is because it is after numpy which installation is not done correctly by pip ?

**Comment by pierre-rouanet** [comment]
There is already the dependency in the setup.py. I guess you are using pypot in develop mode and update it. In this case it does not update the dependency automatically.

BTW, enum34 seems to be the official repo so you should prefer it.

**Comment by matthieu-lapeyre** [comment]
it was installed using pip on a fresh linux instal

**Comment by pierre-rouanet** [comment]
I've just tried on a virtual env without any problem. 
I've just seen your numpy comment. Indeed, if the install fails because of numpy, it probably stops before installing enum.

**Comment by matthieu-lapeyre** [comment]
So maybe it could be fixed just by changing the dependency order

**Comment by show0k** [comment]
Shouldn’t we close this issue ?
