### ISSUE TITLE
Adding the wheel mode control at the robot level

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/pypot#68]
Can we add the wheel mode control to the robot please ? :)

I guess we could add an option in the motor configuration such as allow_wheel_mode = true

Also it would be of course great to be able to change it dynamically in a robot primitive :)

**Comment by pierre-rouanet** [comment]
Fixed by https://github.com/poppy-project/pypot/commit/c494b47d8e67da3318f84def71a409e6741b53e0.
