### ISSUE TITLE
Rest API examples in Ruby

### ISSUE THREAD

**Issue by poqudrof** [poppy-project/pypot#93]
Hello all, 

I did a small ruby code to control Poppy's. It should be model agnositic and get all the motor names, and registers and the possiblity to set the registers. 

Where should I post this ?  Maybe we could create a folder... 
Pypot / samples / REST / ruby / motorControl.rb    . 
If it's ok, I can create a pull request. 

Cheers, 

Jeremy.

**Comment by pierre-rouanet** [comment]
Sounds great!

**Comment by show0k** [comment]
Fix by #94
